[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
